MVC_Task/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading;
using System.Globalization;
using Microsoft.AspNetCore.Http.Extensions;
using System.Threading;

namespace MVC_Task.Controllers
{
    public class LanguageController : BaseController
    {
        public IActionResult Arabic()
        {
            HttpContext.Session.SetString("Lang", "ar-EG");
            return Redirect(HttpContext.Request.Headers["Referer"]);
        }       
        public IActionResult English()
        {
            HttpContext.Session.SetString("Lang", "us-EN");
            return Redirect(HttpContext.Request.Headers["Referer"]);
        }
    }
}

MVC_Task/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_Task.Models;
using MVC_Task.Models.Entities;
using MVC_Task.Services;
using System.Threading;
using System.Globalization;

namespace MVC_Task.Controllers
{
    public class StudentController : BaseController
    {
        readonly IStudent  StudentRepo;
        readonly Pager Pager;

        public StudentController(IStudent _studentRepo,Pager pager)
        {
            StudentRepo = _studentRepo;
            Pager = pager;
        }

        public IActionResult Index( StudentSearch StudentSearch,int page=1)
        {
            List<Student> SelectedStudents;


            const int PageSize = 5;
            if (page < 1)
            {
                page = 1;
            }

            SelectedStudents = StudentRepo.SearchStudent(StudentSearch);

            ViewData["NameFilter"] = StudentSearch.Name;
            ViewData["CityFilter"] = StudentSearch.City;
            ViewData["GenderFilter"] = StudentSearch.Gender;
            ViewData["FromFilter"] = StudentSearch.From;
            ViewData["ToFilter"] = StudentSearch.To;

            int recSkip = (page - 1) * PageSize;
            ViewBag.Students = SelectedStudents.Skip(recSkip).Take(PageSize);
            Pager.setPager(SelectedStudents.Count(), page, PageSize);

            ViewBag.pager = Pager;

            return View();

        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Student student)
        {
            if (!ModelState.IsValid)
            {
                return View(student);
            }
            StudentRepo.AddStudent(student);
            StudentRepo.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? Id)
        {
            if (Id is null)
            {
                return BadRequest();
            }
            else
            {
                Student student = StudentRepo.GetStudentById(Id.Value);
                if (student is null)
                {
                    return NotFound();
                }
                else
                {
                    return View(student);
                }
            }
        }
        [HttpPost]
        public IActionResult Edit(Student Student, Boolean IsEnrolled)
        {
            if (!ModelState.IsValid) {
                return View(Student);            
            }
            Student.IsEnrolled = IsEnrolled;
            StudentRepo.UpdateStudent(Student);
            StudentRepo.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int? Id)
        {
            if (Id is null)
            {
                return BadRequest();
            }
            else
            {
                Student student = StudentRepo.GetStudentById(Id.Value);
                if (student is null)
                {
                    return NotFound();
                }
                else
                {
                    return View(student);
                }
            }
        }
        [HttpPost,ActionName("Delete")]
        public IActionResult DeleteConfirmed(int? Id)
        {
            StudentRepo.DeleteStudent(Id.Value);
            StudentRepo.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC_Task/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_Task</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_Task.styles.css" asp-append-version="true" />
</head>
<body dir="@MVC_Task.Languages.Resource1.dir" >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Student" asp-action="Index">@MVC_Task.Languages.Resource1.Students</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="English">@MVC_Task.Languages.Resource1.English</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Language" asp-action="Arabic">@MVC_Task.Languages.Resource1.Arabic</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>